### ISSUE TITLE
to download data

### ISSUE THREAD

**Issue by tomyputw** [i-cyto/FlowRepositoryQuery#1]
great job! 
I think this package is better than the search tools of FlowRepository, and I wander if there is a better way to download data from it. These become a problem.

**Comment by SamGG** [comment]
Thanks for your feedback. Our package aims to propose a complementary approach to query the amount of data available in FR.

I don't know any way to download the data from FR. I would like a FTP site with all FCS available. I don't see any reason against it. Download used to be faster, but at one point the administrators decided to remove direct download. The proposed solution is not optimal IMHO. If internet bandwith is an issue, the FCS files could compress by group of 1 GB (compressed). If I am correct, the current amount of public FCS is about 5 TB, which is not big and could be compressed in less than 5,000 1 GB files.

All the best.

**Comment by SamGG** [comment]
I closed the issue, but feel free to continue the discussion on Purdue's cytometry list or cytoforum.
If you use FRQ, let us know how you used it, which benefits you get and what could be improved.
